### PR TITLE
fix package.json

### PR DESCRIPTION
**Pull request by BRAYANP**
Now save the name of the app how name in the package.json

### CODE REVIEW

**Comment by eighteyes** [comment]
In `helpers.js` update file does not remove the backup file after it is completed ( see `updateFile' on line 63 ). Please add functionality to remove that backup file.

**Comment by eighteyes** [comment]
@BRAYANP please review and change

**Comment by brianofrokk3r** [comment]
Is this PR still good?

**Comment by BRAYANP** [comment]
Now Yes ! :sweat_smile:

**Pull request merged**
