### PR TITLE
Bt/fix install pi

### PR DESCRIPTION
**Pull request by BRAYANP**

### CODE REVIEW

**Comment by eighteyes** [comment]
@BRAYANP how can i test this?

**Comment by eighteyes** [comment]
I get this error when running locally.

`grep: /etc/os-release: No such file or directory`

**Comment by BRAYANP** [comment]
Hey @eighteyes  ! How can I duplicate the Error ?? `grep: /etc/os-release: No such file or directory`

**Comment by eighteyes** [comment]
Try `npm install` on local machine.

**Pull request merged**
